<?php

namespace Database\Factories;

use App\Enums\BusinessIndustry;
use App\Enums\BusinessType;
use App\Enums\CompanySize;
use App\Enums\ContactRole;
use App\Enums\YearsInBusiness;
use App\Models\Business;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Business>
 */
class BusinessFactory extends Factory
{
    protected $model = Business::class;

    protected $locations = [
        [
            'zip' => '45066',
            'state' => 'OH',
            'county' => 'Warren',
            'city' => 'Springboro',
        ],
        [
            'zip' => '45005',
            'state' => 'OH',
            'county' => 'Warren',
            'city' => 'Franklin',
        ],
        [
            'zip' => '45458',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45036',
            'state' => 'OH',
            'county' => 'Warren',
            'city' => 'Lebanon',
        ],
        [
            'zip' => '45342',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Miamisburg',
        ],
        [
            'zip' => '45343',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Miamisburg',
        ],
        [
            'zip' => '45459',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45449',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45068',
            'state' => 'OH',
            'county' => 'Warren',
            'city' => 'Waynesville',
        ],
        [
            'zip' => '45305',
            'state' => 'OH',
            'county' => 'Greene',
            'city' => 'Bellbrook',
        ],
        [
            'zip' => '45429',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45370',
            'state' => 'OH',
            'county' => 'Greene',
            'city' => 'Spring Valley',
        ],
        [
            'zip' => '45050',
            'state' => 'OH',
            'county' => 'Butler',
            'city' => 'Monroe',
        ],
        [
            'zip' => '45054',
            'state' => 'OH',
            'county' => 'Warren',
            'city' => 'Oregonia',
        ],
        [
            'zip' => '45439',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45327',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Germantown',
        ],
        [
            'zip' => '45440',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45042',
            'state' => 'OH',
            'county' => 'Butler',
            'city' => 'Middletown',
        ],
        [
            'zip' => '45044',
            'state' => 'OH',
            'county' => 'Butler',
            'city' => 'Middletown',
        ],
        [
            'zip' => '45419',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45032',
            'state' => 'OH',
            'county' => 'Warren',
            'city' => 'Harveysburg',
        ],
        [
            'zip' => '45065',
            'state' => 'OH',
            'county' => 'Warren',
            'city' => 'South Lebanon',
        ],
        [
            'zip' => '45409',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45420',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45034',
            'state' => 'OH',
            'county' => 'Warren',
            'city' => 'Kings Mills',
        ],
        [
            'zip' => '45430',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45417',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45040',
            'state' => 'OH',
            'county' => 'Warren',
            'city' => 'Mason',
        ],
        [
            'zip' => '45437',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45067',
            'state' => 'OH',
            'county' => 'Butler',
            'city' => 'Trenton',
        ],
        [
            'zip' => '45410',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45469',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45479',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45325',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Farmersville',
        ],
        [
            'zip' => '45422',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45401',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45412',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45413',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45428',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45470',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45475',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45481',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45482',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45490',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45402',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45441',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45448',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45423',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45039',
            'state' => 'OH',
            'county' => 'Warren',
            'city' => 'Maineville',
        ],
        [
            'zip' => '45152',
            'state' => 'OH',
            'county' => 'Warren',
            'city' => 'Morrow',
        ],
        [
            'zip' => '45432',
            'state' => 'OH',
            'county' => 'Greene',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45301',
            'state' => 'OH',
            'county' => 'Greene',
            'city' => 'Alpha',
        ],
        [
            'zip' => '45434',
            'state' => 'OH',
            'county' => 'Greene',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45403',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45345',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'New Lebanon',
        ],
        [
            'zip' => '45406',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45113',
            'state' => 'OH',
            'county' => 'Clinton',
            'city' => 'Clarksville',
        ],
        [
            'zip' => '45405',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45011',
            'state' => 'OH',
            'county' => 'Butler',
            'city' => 'Hamilton',
        ],
        [
            'zip' => '45055',
            'state' => 'OH',
            'county' => 'Butler',
            'city' => 'Overpeck',
        ],
        [
            'zip' => '45431',
            'state' => 'OH',
            'county' => 'Greene',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45404',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45330',
            'state' => 'OH',
            'county' => 'Preble',
            'city' => 'Gratis',
        ],
        [
            'zip' => '45069',
            'state' => 'OH',
            'county' => 'Butler',
            'city' => 'West Chester',
        ],
        [
            'zip' => '45070',
            'state' => 'OH',
            'county' => 'Preble',
            'city' => 'West Elkton',
        ],
        [
            'zip' => '45071',
            'state' => 'OH',
            'county' => 'Butler',
            'city' => 'West Chester',
        ],
        [
            'zip' => '45416',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45426',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45435',
            'state' => 'OH',
            'county' => 'Greene',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45062',
            'state' => 'OH',
            'county' => 'Butler',
            'city' => 'Seven Mile',
        ],
        [
            'zip' => '45385',
            'state' => 'OH',
            'county' => 'Greene',
            'city' => 'Xenia',
        ],
        [
            'zip' => '45414',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45249',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45433',
            'state' => 'OH',
            'county' => 'Greene',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45415',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45140',
            'state' => 'OH',
            'county' => 'Clermont',
            'city' => 'Loveland',
        ],
        [
            'zip' => '45381',
            'state' => 'OH',
            'county' => 'Preble',
            'city' => 'West Alexandria',
        ],
        [
            'zip' => '45004',
            'state' => 'OH',
            'county' => 'Butler',
            'city' => 'Collinsville',
        ],
        [
            'zip' => '45162',
            'state' => 'OH',
            'county' => 'Warren',
            'city' => 'Pleasant Plain',
        ],
        [
            'zip' => '45012',
            'state' => 'OH',
            'county' => 'Butler',
            'city' => 'Hamilton',
        ],
        [
            'zip' => '45018',
            'state' => 'OH',
            'county' => 'Butler',
            'city' => 'Fairfield',
        ],
        [
            'zip' => '45241',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45064',
            'state' => 'OH',
            'county' => 'Butler',
            'city' => 'Somerville',
        ],
        [
            'zip' => '45384',
            'state' => 'OH',
            'county' => 'Greene',
            'city' => 'Wilberforce',
        ],
        [
            'zip' => '45015',
            'state' => 'OH',
            'county' => 'Butler',
            'city' => 'Hamilton',
        ],
        [
            'zip' => '45424',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45242',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45315',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Clayton',
        ],
        [
            'zip' => '45324',
            'state' => 'OH',
            'county' => 'Greene',
            'city' => 'Fairborn',
        ],
        [
            'zip' => '45246',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45177',
            'state' => 'OH',
            'county' => 'Clinton',
            'city' => 'Wilmington',
        ],
        [
            'zip' => '45309',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Brookville',
        ],
        [
            'zip' => '45122',
            'state' => 'OH',
            'county' => 'Clermont',
            'city' => 'Goshen',
        ],
        [
            'zip' => '45114',
            'state' => 'OH',
            'county' => 'Clinton',
            'city' => 'Cuba',
        ],
        [
            'zip' => '45311',
            'state' => 'OH',
            'county' => 'Preble',
            'city' => 'Camden',
        ],
        [
            'zip' => '45107',
            'state' => 'OH',
            'county' => 'Clinton',
            'city' => 'Blanchester',
        ],
        [
            'zip' => '45014',
            'state' => 'OH',
            'county' => 'Butler',
            'city' => 'Fairfield',
        ],
        [
            'zip' => '45377',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Vandalia',
        ],
        [
            'zip' => '45147',
            'state' => 'OH',
            'county' => 'Clermont',
            'city' => 'Miamiville',
        ],
        [
            'zip' => '45240',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45164',
            'state' => 'OH',
            'county' => 'Clinton',
            'city' => 'Port William',
        ],
        [
            'zip' => '45111',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Camp Dennison',
        ],
        [
            'zip' => '45013',
            'state' => 'OH',
            'county' => 'Butler',
            'city' => 'Hamilton',
        ],
        [
            'zip' => '45215',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45322',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Englewood',
        ],
        [
            'zip' => '45218',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45341',
            'state' => 'OH',
            'county' => 'Clark',
            'city' => 'Medway',
        ],
        [
            'zip' => '45236',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45148',
            'state' => 'OH',
            'county' => 'Clinton',
            'city' => 'Midland',
        ],
        [
            'zip' => '45243',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45323',
            'state' => 'OH',
            'county' => 'Clark',
            'city' => 'Enon',
        ],
        [
            'zip' => '45158',
            'state' => 'OH',
            'county' => 'Clermont',
            'city' => 'Newtonsville',
        ],
        [
            'zip' => '45387',
            'state' => 'OH',
            'county' => 'Greene',
            'city' => 'Yellow Springs',
        ],
        [
            'zip' => '45354',
            'state' => 'OH',
            'county' => 'Montgomery',
            'city' => 'Phillipsburg',
        ],
        [
            'zip' => '45056',
            'state' => 'OH',
            'county' => 'Butler',
            'city' => 'Oxford',
        ],
        [
            'zip' => '45150',
            'state' => 'OH',
            'county' => 'Clermont',
            'city' => 'Milford',
        ],
        [
            'zip' => '45231',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45307',
            'state' => 'OH',
            'county' => 'Greene',
            'city' => 'Bowersville',
        ],
        [
            'zip' => '45371',
            'state' => 'OH',
            'county' => 'Miami',
            'city' => 'Tipp City',
        ],
        [
            'zip' => '45338',
            'state' => 'OH',
            'county' => 'Preble',
            'city' => 'Lewisburg',
        ],
        [
            'zip' => '45320',
            'state' => 'OH',
            'county' => 'Preble',
            'city' => 'Eaton',
        ],
        [
            'zip' => '45335',
            'state' => 'OH',
            'county' => 'Greene',
            'city' => 'Jamestown',
        ],
        [
            'zip' => '45174',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Terrace Park',
        ],
        [
            'zip' => '45237',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45216',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45213',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45316',
            'state' => 'OH',
            'county' => 'Greene',
            'city' => 'Clifton',
        ],
        [
            'zip' => '45146',
            'state' => 'OH',
            'county' => 'Clinton',
            'city' => 'Martinsville',
        ],
        [
            'zip' => '45251',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45061',
            'state' => 'OH',
            'county' => 'Butler',
            'city' => 'Ross',
        ],
        [
            'zip' => '45378',
            'state' => 'OH',
            'county' => 'Preble',
            'city' => 'Verona',
        ],
        [
            'zip' => '45314',
            'state' => 'OH',
            'county' => 'Greene',
            'city' => 'Cedarville',
        ],
        [
            'zip' => '45227',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45003',
            'state' => 'OH',
            'county' => 'Butler',
            'city' => 'College Corner',
        ],
        [
            'zip' => '45252',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45383',
            'state' => 'OH',
            'county' => 'Miami',
            'city' => 'West Milton',
        ],
        [
            'zip' => '45212',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45224',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45209',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45999',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45201',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45221',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45222',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45234',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45250',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45253',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45258',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45262',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45263',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45264',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45268',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45269',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45270',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45271',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45273',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45274',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45277',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45280',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45296',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45298',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45299',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45166',
            'state' => 'OH',
            'county' => 'Clinton',
            'city' => 'Reesville',
        ],
        [
            'zip' => '45319',
            'state' => 'OH',
            'county' => 'Clark',
            'city' => 'Donnelsville',
        ],
        [
            'zip' => '45169',
            'state' => 'OH',
            'county' => 'Clinton',
            'city' => 'Sabina',
        ],
        [
            'zip' => '45160',
            'state' => 'OH',
            'county' => 'Clermont',
            'city' => 'Owensville',
        ],
        [
            'zip' => '45232',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45244',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45217',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45118',
            'state' => 'OH',
            'county' => 'Brown',
            'city' => 'Fayetteville',
        ],
        [
            'zip' => '45063',
            'state' => 'OH',
            'county' => 'Butler',
            'city' => 'Shandon',
        ],
        [
            'zip' => '45239',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45361',
            'state' => 'OH',
            'county' => 'Miami',
            'city' => 'Potsdam',
        ],
        [
            'zip' => '45208',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45229',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45344',
            'state' => 'OH',
            'county' => 'Clark',
            'city' => 'New Carlisle',
        ],
        [
            'zip' => '45207',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45159',
            'state' => 'OH',
            'county' => 'Clinton',
            'city' => 'New Vienna',
        ],
        [
            'zip' => '45506',
            'state' => 'OH',
            'county' => 'Clark',
            'city' => 'Springfield',
        ],
        [
            'zip' => '45103',
            'state' => 'OH',
            'county' => 'Clermont',
            'city' => 'Batavia',
        ],
        [
            'zip' => '45254',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45223',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45220',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45382',
            'state' => 'OH',
            'county' => 'Preble',
            'city' => 'West Manchester',
        ],
        [
            'zip' => '45267',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45235',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45337',
            'state' => 'OH',
            'county' => 'Miami',
            'city' => 'Laura',
        ],
        [
            'zip' => '45247',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45206',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45226',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45339',
            'state' => 'OH',
            'county' => 'Miami',
            'city' => 'Ludlow Falls',
        ],
        [
            'zip' => '45142',
            'state' => 'OH',
            'county' => 'Highland',
            'city' => 'Lynchburg',
        ],
        [
            'zip' => '45053',
            'state' => 'OH',
            'county' => 'Butler',
            'city' => 'Okeana',
        ],
        [
            'zip' => '45321',
            'state' => 'OH',
            'county' => 'Preble',
            'city' => 'Eldorado',
        ],
        [
            'zip' => '41074',
            'state' => 'KY',
            'county' => 'Campbell',
            'city' => 'Dayton',
        ],
        [
            'zip' => '45219',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '47010',
            'state' => 'IN',
            'county' => 'Franklin',
            'city' => 'Bath',
        ],
        [
            'zip' => '45225',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '47003',
            'state' => 'IN',
            'county' => 'Union',
            'city' => 'West College Corner',
        ],
        [
            'zip' => '45245',
            'state' => 'OH',
            'county' => 'Clermont',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45358',
            'state' => 'OH',
            'county' => 'Darke',
            'city' => 'Pitsburg',
        ],
        [
            'zip' => '45504',
            'state' => 'OH',
            'county' => 'Clark',
            'city' => 'Springfield',
        ],
        [
            'zip' => '45211',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '41073',
            'state' => 'KY',
            'county' => 'Campbell',
            'city' => 'Bellevue',
        ],
        [
            'zip' => '45373',
            'state' => 'OH',
            'county' => 'Miami',
            'city' => 'Troy',
        ],
        [
            'zip' => '45230',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45202',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45374',
            'state' => 'OH',
            'county' => 'Miami',
            'city' => 'Troy',
        ],
        [
            'zip' => '45176',
            'state' => 'OH',
            'county' => 'Clermont',
            'city' => 'Williamsburg',
        ],
        [
            'zip' => '45214',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '43142',
            'state' => 'OH',
            'county' => 'Fayette',
            'city' => 'Milledgeville',
        ],
        [
            'zip' => '45501',
            'state' => 'OH',
            'county' => 'Clark',
            'city' => 'Springfield',
        ],
        [
            'zip' => '45349',
            'state' => 'OH',
            'county' => 'Clark',
            'city' => 'North Hampton',
        ],
        [
            'zip' => '45041',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Miamitown',
        ],
        [
            'zip' => '45304',
            'state' => 'OH',
            'county' => 'Darke',
            'city' => 'Arcanum',
        ],
        [
            'zip' => '45255',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '41075',
            'state' => 'KY',
            'county' => 'Campbell',
            'city' => 'Fort Thomas',
        ],
        [
            'zip' => '41072',
            'state' => 'KY',
            'county' => 'Campbell',
            'city' => 'Newport',
        ],
        [
            'zip' => '45203',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45248',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45030',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Harrison',
        ],
        [
            'zip' => '41019',
            'state' => 'KY',
            'county' => 'Kenton',
            'city' => 'Covington',
        ],
        [
            'zip' => '45359',
            'state' => 'OH',
            'county' => 'Miami',
            'city' => 'Pleasant Hill',
        ],
        [
            'zip' => '41071',
            'state' => 'KY',
            'county' => 'Campbell',
            'city' => 'Newport',
        ],
        [
            'zip' => '41012',
            'state' => 'KY',
            'county' => 'Kenton',
            'city' => 'Covington',
        ],
        [
            'zip' => '45505',
            'state' => 'OH',
            'county' => 'Clark',
            'city' => 'Springfield',
        ],
        [
            'zip' => '45205',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45502',
            'state' => 'OH',
            'county' => 'Clark',
            'city' => 'Springfield',
        ],
        [
            'zip' => '45204',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45002',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cleves',
        ],
        [
            'zip' => '43128',
            'state' => 'OH',
            'county' => 'Fayette',
            'city' => 'Jeffersonville',
        ],
        [
            'zip' => '45312',
            'state' => 'OH',
            'county' => 'Miami',
            'city' => 'Casstown',
        ],
        [
            'zip' => '47324',
            'state' => 'IN',
            'county' => 'Wayne',
            'city' => 'Boston',
        ],
        [
            'zip' => '45132',
            'state' => 'OH',
            'county' => 'Highland',
            'city' => 'Highland',
        ],
        [
            'zip' => '41016',
            'state' => 'KY',
            'county' => 'Kenton',
            'city' => 'Covington',
        ],
        [
            'zip' => '41085',
            'state' => 'KY',
            'county' => 'Campbell',
            'city' => 'Silver Grove',
        ],
        [
            'zip' => '45368',
            'state' => 'OH',
            'county' => 'Clark',
            'city' => 'South Charleston',
        ],
        [
            'zip' => '45238',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45389',
            'state' => 'OH',
            'county' => 'Champaign',
            'city' => 'Christiansburg',
        ],
        [
            'zip' => '45347',
            'state' => 'OH',
            'county' => 'Preble',
            'city' => 'New Paris',
        ],
        [
            'zip' => '41014',
            'state' => 'KY',
            'county' => 'Kenton',
            'city' => 'Covington',
        ],
        [
            'zip' => '45102',
            'state' => 'OH',
            'county' => 'Clermont',
            'city' => 'Amelia',
        ],
        [
            'zip' => '47016',
            'state' => 'IN',
            'county' => 'Franklin',
            'city' => 'Cedar Grove',
        ],
        [
            'zip' => '45154',
            'state' => 'OH',
            'county' => 'Brown',
            'city' => 'Mount Orab',
        ],
        [
            'zip' => '41011',
            'state' => 'KY',
            'county' => 'Kenton',
            'city' => 'Covington',
        ],
        [
            'zip' => '45503',
            'state' => 'OH',
            'county' => 'Clark',
            'city' => 'Springfield',
        ],
        [
            'zip' => '47353',
            'state' => 'IN',
            'county' => 'Union',
            'city' => 'Liberty',
        ],
        [
            'zip' => '41099',
            'state' => 'KY',
            'county' => 'Campbell',
            'city' => 'Newport',
        ],
        [
            'zip' => '45135',
            'state' => 'OH',
            'county' => 'Highland',
            'city' => 'Leesburg',
        ],
        [
            'zip' => '41059',
            'state' => 'KY',
            'county' => 'Campbell',
            'city' => 'Melbourne',
        ],
        [
            'zip' => '45372',
            'state' => 'OH',
            'county' => 'Clark',
            'city' => 'Tremont City',
        ],
        [
            'zip' => '45233',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45051',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Mount Saint Joseph',
        ],
        [
            'zip' => '45001',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Addyston',
        ],
        [
            'zip' => '45033',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Hooven',
        ],
        [
            'zip' => '43153',
            'state' => 'OH',
            'county' => 'Madison',
            'city' => 'South Solon',
        ],
        [
            'zip' => '41076',
            'state' => 'KY',
            'county' => 'Campbell',
            'city' => 'Newport',
        ],
        [
            'zip' => '45346',
            'state' => 'OH',
            'county' => 'Darke',
            'city' => 'New Madison',
        ],
        [
            'zip' => '47035',
            'state' => 'IN',
            'county' => 'Franklin',
            'city' => 'New Trenton',
        ],
        [
            'zip' => '47060',
            'state' => 'IN',
            'county' => 'Dearborn',
            'city' => 'West Harrison',
        ],
        [
            'zip' => '41025',
            'state' => 'KY',
            'county' => 'Kenton',
            'city' => 'Erlanger',
        ],
        [
            'zip' => '41021',
            'state' => 'KY',
            'county' => 'Boone',
            'city' => 'Hebron',
        ],
        [
            'zip' => '47375',
            'state' => 'IN',
            'county' => 'Wayne',
            'city' => 'Richmond',
        ],
        [
            'zip' => '41017',
            'state' => 'KY',
            'county' => 'Kenton',
            'city' => 'Ft Mitchell',
        ],
        [
            'zip' => '41048',
            'state' => 'KY',
            'county' => 'Boone',
            'city' => 'Hebron',
        ],
        [
            'zip' => '45052',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'North Bend',
        ],
        [
            'zip' => '45318',
            'state' => 'OH',
            'county' => 'Miami',
            'city' => 'Covington',
        ],
        [
            'zip' => '45326',
            'state' => 'OH',
            'county' => 'Miami',
            'city' => 'Fletcher',
        ],
        [
            'zip' => '43160',
            'state' => 'OH',
            'county' => 'Fayette',
            'city' => 'Washington Court House',
        ],
        [
            'zip' => '45157',
            'state' => 'OH',
            'county' => 'Clermont',
            'city' => 'New Richmond',
        ],
        [
            'zip' => '41015',
            'state' => 'KY',
            'county' => 'Kenton',
            'city' => 'Latonia',
        ],
        [
            'zip' => '47012',
            'state' => 'IN',
            'county' => 'Franklin',
            'city' => 'Brookville',
        ],
        [
            'zip' => '45328',
            'state' => 'OH',
            'county' => 'Darke',
            'city' => 'Gettysburg',
        ],
        [
            'zip' => '47374',
            'state' => 'IN',
            'county' => 'Wayne',
            'city' => 'Richmond',
        ],
        [
            'zip' => '45308',
            'state' => 'OH',
            'county' => 'Miami',
            'city' => 'Bradford',
        ],
        [
            'zip' => '43151',
            'state' => 'OH',
            'county' => 'Madison',
            'city' => 'Sedalia',
        ],
        [
            'zip' => '41018',
            'state' => 'KY',
            'county' => 'Kenton',
            'city' => 'Erlanger',
        ],
        [
            'zip' => '45275',
            'state' => 'OH',
            'county' => 'Hamilton',
            'city' => 'Cincinnati',
        ],
        [
            'zip' => '45106',
            'state' => 'OH',
            'county' => 'Clermont',
            'city' => 'Bethel',
        ],
        [
            'zip' => '43072',
            'state' => 'OH',
            'county' => 'Champaign',
            'city' => 'Saint Paris',
        ],
        [
            'zip' => '47325',
            'state' => 'IN',
            'county' => 'Union',
            'city' => 'Brownsville',
        ],
        [
            'zip' => '45332',
            'state' => 'OH',
            'county' => 'Darke',
            'city' => 'Hollansburg',
        ],
        [
            'zip' => '45369',
            'state' => 'OH',
            'county' => 'Clark',
            'city' => 'South Vienna',
        ],
        [
            'zip' => '45356',
            'state' => 'OH',
            'county' => 'Miami',
            'city' => 'Piqua',
        ],
        [
            'zip' => '45155',
            'state' => 'OH',
            'county' => 'Highland',
            'city' => 'Mowrystown',
        ],
        [
            'zip' => '45133',
            'state' => 'OH',
            'county' => 'Highland',
            'city' => 'Hillsboro',
        ],
        [
            'zip' => '41022',
            'state' => 'KY',
            'county' => 'Boone',
            'city' => 'Florence',
        ],
        [
            'zip' => '45171',
            'state' => 'OH',
            'county' => 'Brown',
            'city' => 'Sardinia',
        ],
        [
            'zip' => '43106',
            'state' => 'OH',
            'county' => 'Fayette',
            'city' => 'Bloomingburg',
        ],
        [
            'zip' => '45317',
            'state' => 'OH',
            'county' => 'Miami',
            'city' => 'Conover',
        ],
        [
            'zip' => '43083',
            'state' => 'OH',
            'county' => 'Champaign',
            'city' => 'Westville',
        ],
        [
            'zip' => '45331',
            'state' => 'OH',
            'county' => 'Darke',
            'city' => 'Greenville',
        ],
        [
            'zip' => '45352',
            'state' => 'OH',
            'county' => 'Darke',
            'city' => 'Palestine',
        ],
        [
            'zip' => '47025',
            'state' => 'IN',
            'county' => 'Dearborn',
            'city' => 'Lawrenceburg',
        ],
        [
            'zip' => '41001',
            'state' => 'KY',
            'county' => 'Campbell',
            'city' => 'Alexandria',
        ],
        [
            'zip' => '43010',
            'state' => 'OH',
            'county' => 'Clark',
            'city' => 'Catawba',
        ],
        [
            'zip' => '41007',
            'state' => 'KY',
            'county' => 'Campbell',
            'city' => 'California',
        ],
        [
            'zip' => '41042',
            'state' => 'KY',
            'county' => 'Boone',
            'city' => 'Florence',
        ],
        [
            'zip' => '47022',
            'state' => 'IN',
            'county' => 'Dearborn',
            'city' => 'Guilford',
        ],
        [
            'zip' => '47392',
            'state' => 'IN',
            'county' => 'Wayne',
            'city' => 'Webster',
        ],
        [
            'zip' => '45130',
            'state' => 'OH',
            'county' => 'Brown',
            'city' => 'Hamersville',
        ],
        [
            'zip' => '47330',
            'state' => 'IN',
            'county' => 'Wayne',
            'city' => 'Centerville',
        ],
        [
            'zip' => '43078',
            'state' => 'OH',
            'county' => 'Champaign',
            'city' => 'Urbana',
        ],
        [
            'zip' => '47341',
            'state' => 'IN',
            'county' => 'Wayne',
            'city' => 'Fountain City',
        ],
        [
            'zip' => '41051',
            'state' => 'KY',
            'county' => 'Kenton',
            'city' => 'Independence',
        ],
        [
            'zip' => '41005',
            'state' => 'KY',
            'county' => 'Boone',
            'city' => 'Burlington',
        ],
        [
            'zip' => '41080',
            'state' => 'KY',
            'county' => 'Boone',
            'city' => 'Petersburg',
        ],
        [
            'zip' => '45123',
            'state' => 'OH',
            'county' => 'Highland',
            'city' => 'Greenfield',
        ],
        [
            'zip' => '45153',
            'state' => 'OH',
            'county' => 'Clermont',
            'city' => 'Moscow',
        ],
        [
            'zip' => '45119',
            'state' => 'OH',
            'county' => 'Brown',
            'city' => 'Feesburg',
        ],
        [
            'zip' => '47030',
            'state' => 'IN',
            'county' => 'Franklin',
            'city' => 'Metamora',
        ],
        [
            'zip' => '43070',
            'state' => 'OH',
            'county' => 'Champaign',
            'city' => 'Rosewood',
        ],
        [
            'zip' => '41053',
            'state' => 'KY',
            'county' => 'Kenton',
            'city' => 'Kenton',
        ],
        [
            'zip' => '45333',
            'state' => 'OH',
            'county' => 'Shelby',
            'city' => 'Houston',
        ],
        [
            'zip' => '45121',
            'state' => 'OH',
            'county' => 'Brown',
            'city' => 'Georgetown',
        ],
        [
            'zip' => '45363',
            'state' => 'OH',
            'county' => 'Shelby',
            'city' => 'Russia',
        ],
        [
            'zip' => '41063',
            'state' => 'KY',
            'county' => 'Kenton',
            'city' => 'Morning View',
        ],
        [
            'zip' => '47331',
            'state' => 'IN',
            'county' => 'Fayette',
            'city' => 'Connersville',
        ],
        [
            'zip' => '45120',
            'state' => 'OH',
            'county' => 'Clermont',
            'city' => 'Felicity',
        ],
        [
            'zip' => '47345',
            'state' => 'IN',
            'county' => 'Wayne',
            'city' => 'Greens Fork',
        ],
        [
            'zip' => '43140',
            'state' => 'OH',
            'county' => 'Madison',
            'city' => 'London',
        ],
        [
            'zip' => '47393',
            'state' => 'IN',
            'county' => 'Wayne',
            'city' => 'Williamsburg',
        ],
        [
            'zip' => '41094',
            'state' => 'KY',
            'county' => 'Boone',
            'city' => 'Walton',
        ],
        [
            'zip' => '43044',
            'state' => 'OH',
            'county' => 'Champaign',
            'city' => 'Mechanicsburg',
        ],
        [
            'zip' => '41091',
            'state' => 'KY',
            'county' => 'Boone',
            'city' => 'Union',
        ],
        [
            'zip' => '45380',
            'state' => 'OH',
            'county' => 'Darke',
            'city' => 'Versailles',
        ],
        [
            'zip' => '45365',
            'state' => 'OH',
            'county' => 'Shelby',
            'city' => 'Sidney',
        ],
        [
            'zip' => '45156',
            'state' => 'OH',
            'county' => 'Clermont',
            'city' => 'Neville',
        ],
        [
            'zip' => '47024',
            'state' => 'IN',
            'county' => 'Franklin',
            'city' => 'Laurel',
        ],
        [
            'zip' => '43143',
            'state' => 'OH',
            'county' => 'Madison',
            'city' => 'Mount Sterling',
        ],
        [
            'zip' => '45367',
            'state' => 'OH',
            'county' => 'Shelby',
            'city' => 'Sidney',
        ],
        [
            'zip' => '47355',
            'state' => 'IN',
            'county' => 'Randolph',
            'city' => 'Lynn',
        ],
        [
            'zip' => '47357',
            'state' => 'IN',
            'county' => 'Wayne',
            'city' => 'Milton',
        ],
        [
            'zip' => '47041',
            'state' => 'IN',
            'county' => 'Ripley',
            'city' => 'Sunman',
        ],
        [
            'zip' => '43145',
            'state' => 'OH',
            'county' => 'Pickaway',
            'city' => 'New Holland',
        ],
        [
            'zip' => '45303',
            'state' => 'OH',
            'county' => 'Darke',
            'city' => 'Ansonia',
        ],
        [
            'zip' => '47001',
            'state' => 'IN',
            'county' => 'Dearborn',
            'city' => 'Aurora',
        ],
        [
            'zip' => '45697',
            'state' => 'OH',
            'county' => 'Adams',
            'city' => 'Winchester',
        ],
        [
            'zip' => '47370',
            'state' => 'IN',
            'county' => 'Wayne',
            'city' => 'Pershing',
        ],
        [
            'zip' => '43009',
            'state' => 'OH',
            'county' => 'Champaign',
            'city' => 'Cable',
        ],
        [
            'zip' => '41006',
            'state' => 'KY',
            'county' => 'Pendleton',
            'city' => 'Butler',
        ],
        [
            'zip' => '45112',
            'state' => 'OH',
            'county' => 'Clermont',
            'city' => 'Chilo',
        ],
        [
            'zip' => '45679',
            'state' => 'OH',
            'county' => 'Adams',
            'city' => 'Seaman',
        ],
        [
            'zip' => '45353',
            'state' => 'OH',
            'county' => 'Shelby',
            'city' => 'Pemberton',
        ],
        [
            'zip' => '45624',
            'state' => 'OH',
            'county' => 'Pike',
            'city' => 'Cynthiana',
        ],
        [
            'zip' => '47339',
            'state' => 'IN',
            'county' => 'Wayne',
            'city' => 'Economy',
        ],
        [
            'zip' => '45390',
            'state' => 'OH',
            'county' => 'Darke',
            'city' => 'Union City',
        ],
        [
            'zip' => '45131',
            'state' => 'OH',
            'county' => 'Brown',
            'city' => 'Higginsport',
        ],
        [
            'zip' => '47033',
            'state' => 'IN',
            'county' => 'Ripley',
            'city' => 'Morris',
        ],
        [
            'zip' => '45168',
            'state' => 'OH',
            'county' => 'Brown',
            'city' => 'Russellville',
        ],
        [
            'zip' => '47032',
            'state' => 'IN',
            'county' => 'Dearborn',
            'city' => 'Moores Hill',
        ],
        [
            'zip' => '47327',
            'state' => 'IN',
            'county' => 'Wayne',
            'city' => 'Cambridge City',
        ],
        [
            'zip' => '45360',
            'state' => 'OH',
            'county' => 'Shelby',
            'city' => 'Port Jefferson',
        ],
        [
            'zip' => '45628',
            'state' => 'OH',
            'county' => 'Ross',
            'city' => 'Frankfort',
        ],
        [
            'zip' => '43343',
            'state' => 'OH',
            'county' => 'Logan',
            'city' => 'Quincy',
        ],
        [
            'zip' => '45845',
            'state' => 'OH',
            'county' => 'Shelby',
            'city' => 'Fort Loramie',
        ],
        [
            'zip' => '41043',
            'state' => 'KY',
            'county' => 'Bracken',
            'city' => 'Foster',
        ],
        [
            'zip' => '43357',
            'state' => 'OH',
            'county' => 'Logan',
            'city' => 'West Liberty',
        ],
        [
            'zip' => '43047',
            'state' => 'OH',
            'county' => 'Champaign',
            'city' => 'Mingo',
        ],
        [
            'zip' => '45362',
            'state' => 'OH',
            'county' => 'Darke',
            'city' => 'Rossburg',
        ],
        [
            'zip' => '43318',
            'state' => 'OH',
            'county' => 'Logan',
            'city' => 'De Graff',
        ],
        [
            'zip' => '45388',
            'state' => 'OH',
            'county' => 'Darke',
            'city' => 'Yorkshire',
        ],
        [
            'zip' => '47036',
            'state' => 'IN',
            'county' => 'Franklin',
            'city' => 'Oldenburg',
        ],
        [
            'zip' => '43084',
            'state' => 'OH',
            'county' => 'Champaign',
            'city' => 'Woodstock',
        ],
        [
            'zip' => '47335',
            'state' => 'IN',
            'county' => 'Wayne',
            'city' => 'Dublin',
        ],
        [
            'zip' => '45172',
            'state' => 'OH',
            'county' => 'Highland',
            'city' => 'Sinking Spring',
        ],
        [
            'zip' => '45681',
            'state' => 'OH',
            'county' => 'Ross',
            'city' => 'South Salem',
        ],
        [
            'zip' => '47006',
            'state' => 'IN',
            'county' => 'Ripley',
            'city' => 'Batesville',
        ],
        [
            'zip' => '47322',
            'state' => 'IN',
            'county' => 'Fayette',
            'city' => 'Bentonville',
        ],
        [
            'zip' => '43162',
            'state' => 'OH',
            'county' => 'Madison',
            'city' => 'West Jefferson',
        ],
        [
            'zip' => '41030',
            'state' => 'KY',
            'county' => 'Grant',
            'city' => 'Crittenden',
        ],
        [
            'zip' => '45618',
            'state' => 'OH',
            'county' => 'Adams',
            'city' => 'Cherry Fork',
        ],
        [
            'zip' => '47390',
            'state' => 'IN',
            'county' => 'Randolph',
            'city' => 'Union City',
        ],
        [
            'zip' => '43117',
            'state' => 'OH',
            'county' => 'Pickaway',
            'city' => 'Derby',
        ],
        [
            'zip' => '41033',
            'state' => 'KY',
            'county' => 'Pendleton',
            'city' => 'De Mossville',
        ],
        [
            'zip' => '45612',
            'state' => 'OH',
            'county' => 'Ross',
            'city' => 'Bainbridge',
        ],
        [
            'zip' => '43029',
            'state' => 'OH',
            'county' => 'Union',
            'city' => 'Irwin',
        ],
        [
            'zip' => '41092',
            'state' => 'KY',
            'county' => 'Boone',
            'city' => 'Verona',
        ],
        [
            'zip' => '45351',
            'state' => 'OH',
            'county' => 'Darke',
            'city' => 'Osgood',
        ],
        [
            'zip' => '43115',
            'state' => 'OH',
            'county' => 'Ross',
            'city' => 'Clarksburg',
        ],
        [
            'zip' => '47346',
            'state' => 'IN',
            'county' => 'Wayne',
            'city' => 'Hagerstown',
        ],
        [
            'zip' => '45350',
            'state' => 'OH',
            'county' => 'Darke',
            'city' => 'North Star',
        ],
        [
            'zip' => '47031',
            'state' => 'IN',
            'county' => 'Ripley',
            'city' => 'Milan',
        ],
        [
            'zip' => '45340',
            'state' => 'OH',
            'county' => 'Shelby',
            'city' => 'Maplewood',
        ],
        [
            'zip' => '45348',
            'state' => 'OH',
            'county' => 'Darke',
            'city' => 'New Weston',
        ],
        [
            'zip' => '46133',
            'state' => 'IN',
            'county' => 'Fayette',
            'city' => 'Glenwood',
        ],
        [
            'zip' => '43060',
            'state' => 'OH',
            'county' => 'Champaign',
            'city' => 'North Lewisburg',
        ],
        [
            'zip' => '45115',
            'state' => 'OH',
            'county' => 'Brown',
            'city' => 'Decatur',
        ],
        [
            'zip' => '45167',
            'state' => 'OH',
            'county' => 'Brown',
            'city' => 'Ripley',
        ],
        [
            'zip' => '47040',
            'state' => 'IN',
            'county' => 'Ohio',
            'city' => 'Rising Sun',
        ],
        [
            'zip' => '45865',
            'state' => 'OH',
            'county' => 'Auglaize',
            'city' => 'Minster',
        ],
        [
            'zip' => '41002',
            'state' => 'KY',
            'county' => 'Bracken',
            'city' => 'Augusta',
        ],
        [
            'zip' => '45646',
            'state' => 'OH',
            'county' => 'Pike',
            'city' => 'Latham',
        ],
        [
            'zip' => '47039',
            'state' => 'IN',
            'county' => 'Ripley',
            'city' => 'Pierceville',
        ],
        [
            'zip' => '43146',
            'state' => 'OH',
            'county' => 'Pickaway',
            'city' => 'Orient',
        ],
        [
            'zip' => '45302',
            'state' => 'OH',
            'county' => 'Shelby',
            'city' => 'Anna',
        ],
        [
            'zip' => '47358',
            'state' => 'IN',
            'county' => 'Randolph',
            'city' => 'Modoc',
        ],
        [
            'zip' => '47394',
            'state' => 'IN',
            'county' => 'Randolph',
            'city' => 'Winchester',
        ],
        [
            'zip' => '43164',
            'state' => 'OH',
            'county' => 'Pickaway',
            'city' => 'Williamsport',
        ],
        [
            'zip' => '46127',
            'state' => 'IN',
            'county' => 'Rush',
            'city' => 'Falmouth',
        ],
        [
            'zip' => '47366',
            'state' => 'IN',
            'county' => 'Henry',
            'city' => 'New Lisbon',
        ],
        [
            'zip' => '47038',
            'state' => 'IN',
            'county' => 'Switzerland',
            'city' => 'Patriot',
        ],
        [
            'zip' => '45660',
            'state' => 'OH',
            'county' => 'Adams',
            'city' => 'Peebles',
        ],
        [
            'zip' => '47018',
            'state' => 'IN',
            'county' => 'Dearborn',
            'city' => 'Dillsboro',
        ],
        [
            'zip' => '47387',
            'state' => 'IN',
            'county' => 'Henry',
            'city' => 'Straughn',
        ],
        [
            'zip' => '45617',
            'state' => 'OH',
            'county' => 'Ross',
            'city' => 'Bourneville',
        ],
        [
            'zip' => '45310',
            'state' => 'OH',
            'county' => 'Mercer',
            'city' => 'Burkettsville',
        ],
        [
            'zip' => '47382',
            'state' => 'IN',
            'county' => 'Randolph',
            'city' => 'Saratoga',
        ],
        [
            'zip' => '47019',
            'state' => 'IN',
            'county' => 'Switzerland',
            'city' => 'East Enterprise',
        ],
        [
            'zip' => '41062',
            'state' => 'KY',
            'county' => 'Mason',
            'city' => 'Minerva',
        ],
        [
            'zip' => '47225',
            'state' => 'IN',
            'county' => 'Decatur',
            'city' => 'Clarksburg',
        ],
        [
            'zip' => '45860',
            'state' => 'OH',
            'county' => 'Mercer',
            'city' => 'Maria Stein',
        ],
        [
            'zip' => '43119',
            'state' => 'OH',
            'county' => 'Franklin',
            'city' => 'Galloway',
        ],
        [
            'zip' => '41034',
            'state' => 'KY',
            'county' => 'Mason',
            'city' => 'Dover',
        ],
        [
            'zip' => '43360',
            'state' => 'OH',
            'county' => 'Logan',
            'city' => 'Zanesfield',
        ],
        [
            'zip' => '47263',
            'state' => 'IN',
            'county' => 'Decatur',
            'city' => 'New Point',
        ],
        [
            'zip' => '45336',
            'state' => 'OH',
            'county' => 'Shelby',
            'city' => 'Kettlersville',
        ],
        [
            'zip' => '41004',
            'state' => 'KY',
            'county' => 'Bracken',
            'city' => 'Brooksville',
        ],
        [
            'zip' => '43336',
            'state' => 'OH',
            'county' => 'Logan',
            'city' => 'Middleburg',
        ],
        [
            'zip' => '43077',
            'state' => 'OH',
            'county' => 'Union',
            'city' => 'Unionville Center',
        ],
        [
            'zip' => '45334',
            'state' => 'OH',
            'county' => 'Shelby',
            'city' => 'Jackson Center',
        ],
        [
            'zip' => '41040',
            'state' => 'KY',
            'county' => 'Pendleton',
            'city' => 'Falmouth',
        ],
    ];

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $location = $this->faker->randomElement($this->locations);

        return [
            'name' => $this->faker->company(),
            'email' => $this->faker->companyEmail(),
            'phone' => $this->faker->phoneNumber(),
            'website' => $this->faker->url(),
            'primary_contact' => $this->faker->name(),
            'contact_role' => $this->faker->randomElement(ContactRole::cases())->value,
            'maturity' => $this->faker->randomElement(YearsInBusiness::cases())->value,
            'size' => $this->faker->randomElement(CompanySize::cases())->value,
            'type' => $this->faker->randomElement(BusinessType::cases()),
            'industry' => $this->faker->randomElement(BusinessIndustry::cases()),
            'description' => $this->faker->paragraph(),
            'selling_points' => $this->faker->sentence(),
            'city' => $location['city'],
            'state' => $location['state'],
            'postal_code' => $location['zip'],
            'target_age_range' => $this->faker->randomElements(['18-24', '25-34', '35-44', '45-54'], $this->faker->numberBetween(1, 3)),
            'target_gender' => $this->faker->randomElements(['male', 'female', 'non-binary'], $this->faker->numberBetween(1, 2)),
            'business_goals' => $this->faker->randomElements(['brand_awareness', 'product_promotion', 'growth_scaling'], $this->faker->numberBetween(1, 3)),
            'platforms' => $this->faker->randomElements(['instagram', 'facebook', 'tiktok', 'youtube'], $this->faker->numberBetween(1, 4)),
            'onboarding_complete' => false,
        ];
    }
}
