name: Deploy to Production

on:
  release:
    types: [published]

jobs:
  check-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check if main branch tests are passing
        uses: actions/github-script@v7
        with:
          script: |
            const { data: workflowRuns } = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'tests.yml',
              branch: 'main',
              status: 'completed',
              per_page: 1
            });

            if (workflowRuns.total_count === 0) {
              core.setFailed('No test runs found for main branch');
              return;
            }

            const latestRun = workflowRuns.workflow_runs[0];

            if (latestRun.conclusion !== 'success') {
              core.setFailed(`Latest test run on main branch failed with status: ${latestRun.conclusion}`);
              return;
            }

            console.log(`✅ Main branch tests are passing (Run #${latestRun.run_number})`);

  deploy:
    needs: check-tests
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: none

      - name: Require Laravel Forge CLI
        run: composer global require laravel/forge-cli

      - name: Deploy Site
        run: |
          forge server:switch ${{ secrets.FORGE_SERVER_NAME }}
          forge deploy ${{ secrets.FORGE_SITE_NAME }}
        env:
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}

      - name: Deployment complete
        run: echo "🚀 Deployment triggered successfully for release ${{ github.event.release.tag_name }}"
